name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'  # Ejecutar el workflow cuando se empuja un tag que sigue el formato de versionado semántico

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # O la versión de Node.js que prefieras
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Ejecuta el script de construcción definido en package.json

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Utiliza el token de npm guardado en los secretos de GitHub